definitions:
  models.CreateSong:
    properties:
      group:
        maxLength: 20
        minLength: 2
        type: string
      song:
        minLength: 2
        type: string
    required:
    - group
    - song
    type: object
  models.SongsResponse:
    properties:
      group_song:
        type: string
      id:
        type: integer
      link:
        type: string
      release_date:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
  description: This project was developed as part of a test assignment from Effective
    Mobile
  title: Online Song Library
  version: "1.0"
paths:
  /song/all:
    get:
      consumes:
      - application/json
      description: get all saved songs
      operationId: get-all-song
      parameters:
      - description: Enter the entry id in the table
        in: query
        name: id
        required: true
        type: string
      - description: Enter the number of songs to output
        in: query
        name: limit
        required: true
        type: string
      - description: Enter the column name
        in: query
        name: filter
        type: string
      - description: Enter the required column value
        in: query
        name: value
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SongsResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get All Song
      tags:
      - songs
  /song/create:
    post:
      consumes:
      - application/json
      description: add a new song
      operationId: add-song
      parameters:
      - description: You need to specify the name of the band and the song in the
          request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateSong'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add Song
      tags:
      - songs
  /song/delete/{id}:
    delete:
      consumes:
      - application/json
      description: delete a song from the library
      operationId: delete-song
      parameters:
      - description: Enter the ID of the saved song
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete Song
      tags:
      - songs
  /song/get/{id}:
    get:
      consumes:
      - application/json
      description: get the lyrics by id
      operationId: get-lyrics-song
      parameters:
      - description: Enter the ID of the saved song
        in: path
        name: id
        required: true
        type: integer
      - description: Enter the verse number of the song
        in: query
        name: verse
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Lyrics Song
      tags:
      - songs
  /song/update/{id}:
    patch:
      consumes:
      - application/json
      description: update information about a saved song
      operationId: update-song
      parameters:
      - description: Enter the song ID
        in: path
        name: id
        required: true
        type: integer
      - description: You need to specify the name of the band and the song in the
          request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SongsResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update Song
      tags:
      - songs
swagger: "2.0"
